### ISSUE TITLE
`Node.synthesize()` should delegate nested syntheses to subconstructs

### ISSUE THREAD

**Issue by rix0rrr** [aws/constructs#109]
`Node.synthesize()` decides what constructs that it will synthesize into the CURRENT CloudAssembly, and it will select all constructs underneath itself that are synthesizable, and it will synthesize from the leaves to the root.

This makes it impossible to make an intermediary construct which synthesizes its childen into a different Cloud Assembly.

Consider the following:

```
       App
         \
        Stage
           \
          Child
```

When `app.synth()` is called, the first thing it will do is call `child.synthesize()` to synthesize that child into the given Cloud Assembly. This is a problem, as `Stage` would have wanted to create a sub-cloud assembly and synthesize Child into *that*.

Even if we had ordered the children differently, that would not have helped. We would have synthesized `Stage` first, and then Stage could synthesize `Child` into the inner Cloud Assembly. That's a good start, but then subsequently `App` would have synthesized `Child` *again* into the root cloud assembly, which is wrong.

At least if we had had the latter order we could have done some JavaScript hackery to replace the `synthesize` method on `Child` with a no-op function.

-------------------------

The right solution would have been for `Node.synthesize()` is to iterate through its subtree top-down, invoke `synthesize()` on constructs that implement it, and then *stop iterating*. It's then up to the constructs that synthesize themselves on what to do with their own subtree (recurse or not, and in which fashion they should recurse).

Another solution is to have `Node.synthesize()` invoke synthesize on its own direct children, and have the default implementation recurse to its children, and so on, and always do full recursion.

**Comment by eladb** [comment]
We are planning to deprecate synthesis from this layer.
