### ISSUE TITLE
Constructs.isConstruct not working.

### ISSUE THREAD

**Issue by michanto** [aws/constructs#1403]
I’m having trouble getting Construct.isConstruct to work.  Every construct is supposed to have the CONSTRUCT_SYM defined, but when I try to enumerate the symbols of a Stack I get:

Code:
 ```
console.log(JSON.stringify(Object.getOwnPropertySymbols(this).map( s => s.toString() ?? "undefined")))
```

Result:
```
 ["Symbol(@aws-cdk/core.DependableTrait)","Symbol(@aws-cdk/core.Stack)"]
```

Same thing when I do it to a construct:
```
let subScope = new Construct(this, "AScope") 
console.log(JSON.stringify(Object.getOwnPropertySymbols(subScope).map( s => s.toString() ?? "undefined")))
```
Result:
```
["Symbol(@aws-cdk/core.DependableTrait)"]
```

I was expecting to see “Symbol(constructs.Construct)” in that list. What is wrong?
I am using constructs 10.1.176 and aws-cdk-lib 2.53.0 
My library (which calls Constructs.isConstruct) is using constructs 10.0.97.
As is, Constructs.isConstruct only works if I'm using the same Construct library version.  Which is I think wrong.

**Comment by rix0rrr** [comment]
Can't repro this:

package.json

```
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "bla.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
      "constructs_old": "npm:constructs@10.0.97",
      "constructs_new": "npm:constructs@10.1.176"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

test.js:

```
test.js
const constructs_old = require('constructs_old');
const constructs_new = require('constructs_new');


const old = new constructs_old.Construct();
const new_ = new constructs_new.Construct();

console.log(constructs_old.Construct.isConstruct(old));
console.log(constructs_old.Construct.isConstruct(new_));
console.log(constructs_new.Construct.isConstruct(old));
console.log(constructs_new.Construct.isConstruct(new_));
```

Running it:

```
$ node test
true
true
true
true
```

**Comment by rix0rrr** [comment]
Can you provide a minimal reproducing example?

**Comment by michanto** [comment]
I believe the issue is that my first package is JSII, and my second package is TSC.  I will try to come up with a repro.

**Comment by michanto** [comment]
Fixed here:  https://github.com/aws/constructs/commit/bef8e4db061b6f6fc0d08fee9a1fe61673223771
