### ISSUE TITLE
Too easy to have bad dependency versions and errors are confusing

### ISSUE THREAD

**Issue by mbonig** [aws/constructs#1567]
Was recently working on an update to some cdk8s code and ran into an issue where I was using a jsii-library I had previously compiled to earlier versions of cdk8s and constructs. After the upgrade the construct was failing on the consumer side with an obscure error around this code:

https://github.com/aws/constructs/blob/10.x/src/construct.ts#L71

It was ultimately caused by the consuming code using an older version of the constructs library.

I recommend an error get added here to check and suggest a solution.

**Comment by mrgrain** [comment]
@mbonig I don't think I follow your proposed fix. The [PR](https://github.com/aws/constructs/pull/1568/files) as it was adds an error to 10.x of constructs. Someone using 3.x won't ever get that.

Do you recall your situation? I'd like to understand better what happened before attempting a fix.

**Comment by mbonig** [comment]
I don't, as this was over 18 months ago. Feel free to close it.
