### ISSUE TITLE
My build is broken with latest constructs.

### ISSUE THREAD

**Issue by sobolk** [aws/constructs#1612]
Why did you guys move runtime condition without major version bump? Isn't this a breaking change ?

My tests started to fail with right after you guys shipped. I do have `^` here https://github.com/aws-amplify/amplify-cli/blob/f5cebf532894bf4a22d9f938933c38fc4f8e4b1a/packages/amplify-category-custom/resources/package.json#L13 . I would expect that when you ship minor or patch version increment my environment doesn't just break.

```
error constructs@10.1.285: The engine \"node\" is incompatible with this module. Expected version \">= 14.18.0\".
```

Looks like it went out here https://github.com/aws/constructs/pull/1611 .

**Comment by mrgrain** [comment]
Same as https://github.com/aws/constructs/issues/1329
