### ISSUE TITLE
Version `10.1.301` not available on NuGet / Maven

### ISSUE THREAD

**Issue by ansgarm** [aws/constructs#1643]
Hi! We're seeing [errors in our builds](https://github.com/hashicorp/terraform-cdk/actions/runs/4605111665/jobs/8136761315#step:12:77) because the latest publish to NuGet (and Maven) [seems to have failed](https://github.com/aws/constructs/actions/runs/4602504155/jobs/8132108306) which cause an inconsistency in versions available on NPM vs e.g. NuGet.

**Comment by mrgrain** [comment]
Both were eventually published. Closing.

https://repo1.maven.org/maven2/software/constructs/constructs/10.1.301/
https://www.nuget.org/packages/Constructs/10.1.301
