### ISSUE TITLE
stabilize tryRemoveChild()

### ISSUE THREAD

**Issue by pahud** [aws/constructs#2267]
This method was introduced in 2020 from[ this PR](https://github.com/aws/aws-cdk/pull/5608) and aws-cdk-lib has some [adoption](https://github.com/search?q=repo%3Aaws%2Faws-cdk+tryRemoveChild&type=code). As it's still marked as experimental, we've seen customers having concern about that in production but we don't seem to have other methods to remove a child from a Node.

https://github.com/aws/constructs/blob/80aa12204eb07259b9334564977987e79feb733b/src/construct.ts#L369-L379

Please stabilize this method and remove the `@experimental ` tag.

**Comment by ArchitGajjar** [comment]
Hi @pahud - can I work on this issue ? this will be my first contribution into AWS :)

**Comment by mrgrain** [comment]
PRs are welcome!
