### ISSUE TITLE
If multiple version of construct exists in node_modules some Constructs will not be prepared

### ISSUE THREAD

**Issue by apalumbo** [aws/constructs#32]
I was developing a custom cdk constructs library (NestedStacks) and after the upgrade to a version > 1.28 stacks imported from my library are not prepared. The issue was due to the fact that I was using 
`npm link` to test locally the library, in this case a copy of the dependencies exists in the node_module under the linked path.

I found the source of the problem in the implementation of the prepare() method on Construct in this library. `instanceof` breaks in this case so it would be better to use a type guard function (in the previous versions of cdk.Construct was handled in this way)

Using npm pack and then install the tar.gz file is a good temporary workaround.

**Comment by skinny85** [comment]
+1 to changing this - this behavior has just bitten somebody using the CDK with Lerna: https://github.com/aws/aws-cdk/issues/7161
