### ISSUE TITLE
Suspicious release history

### ISSUE THREAD

**Issue by jarikujansuu** [aws/constructs#557]
In our project dependabot wanted to update `constructs` from 3.2.71 to 7.0.1, but change history and commits in repository point to 3.3.* range. Also version history in https://pypi.org/project/constructs/#history looks quite suspicious

**Comment by eladb** [comment]
Thanks for bringing this to our attention. We accidentally released some versions without intention. Let me check if we can deprecate them in PyPI.

**Comment by eladb** [comment]
Deleted PyPI releases.
