### ISSUE TITLE
maven constructs versions 

### ISSUE THREAD

**Issue by peterb154** [aws/constructs#783]
The `constructs` package versions `3.3.118` through `3.3.158` are missing from the maven manifest starting on 10/07/2021
https://repo.maven.apache.org/maven2/software/constructs/constructs/maven-metadata.xml 
![image](https://user-images.githubusercontent.com/989984/136859916-fc01938a-8eaf-4b8b-88bb-d960eaf57d89.png)

yet those versions exists in the package directory: ( https://repo.maven.apache.org/maven2/software/constructs/constructs/3.3.124/ for example) and in other language repos like pypy, npm and nuget. 

Our company uses jsii-pacmak to compile and publishe cdk constructs internally for developer use. We have a standard practice of pinning the version of aws cdk constructs packages and the aws construct library to a specific version to ensure consistent build and usage. We were using aws cdk 1.118.0 and constructs version 3.3.124. We new need to do an emergency upgrade to something 3.3.159 or later. 

If these versions were removed accidentally from maven, can they be added back? Our published java packages that have this version pinned are broken. 

If these versions were removed intentionally, can we get an explaination as to why? Secondary question: is not a good practice to pin the constructs library version. I notice that aws cdk project does not. ex: https://github.com/aws/aws-cdk/blob/v1.118.0/packages/@aws-cdk/core/package.json#L193  

Thank you

**Comment by eladb** [comment]
@peterb154 apologies for taking such a long time to respond. Is this still an issue?

We have just released constructs 10.x as `latest`.

**Comment by peterb154** [comment]
@eladb thanks for the response. Our issue was resolved by upgrading the @aws-cdk version to 1.127.0 that we use for publishing our constructs. This upgraded the the latest 3.x version of the constructs library which exists in the maven repo. 

You mentioned that constructs v10.x is released. But @aws-cdk still uses constructs "^3.3.69"  https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/package.json#L199
![image](https://user-images.githubusercontent.com/989984/145595247-8921b2e8-ecd6-454c-bddd-1d8a6b92494d.png)

**Comment by eladb** [comment]
@peterb154 Indeed CDK v1 will continue to depend on constructs v3 while CDK v2 depends on construct v10.

**Comment by Chriscbr** [comment]
Small correction: CDK v1 will continue to depend on constructs **v3**.
