### ISSUE TITLE
Are npm latest releases correct?

### ISSUE THREAD

**Issue by lenkan** [aws/constructs#784]
See https://www.npmjs.com/package/constructs

![image](https://user-images.githubusercontent.com/5889538/144645794-e3bdcec0-dd1b-41a4-b0d0-ab377a1717bc.png)

Is it intentional to mark 3.3.161 as 'latest' ? This version seems incompatible with new `aws-cdk@2`, it was crashing with `TypeError`. Explicitly installing `10.0.9` solved the problem for me.

**Comment by eladb** [comment]
Thanks for reporting this. Yes v2 requires ^10.

We will move the latest dist tag to 10.x now.

Copy @njlynch

**Comment by eladb** [comment]
We now release 10.x as `latest` and `3.x` as `latest-3`.
