### ISSUE TITLE
Deno compatible

### ISSUE THREAD

**Issue by yordis** [aws/constructs#817]
Hey folks, I would like to use the package from Deno, but it uses some NodeJS API https://github.com/aws/constructs/blob/ede084cf6d7c01e3fb702a8234e92290a786aef4/src/private/uniqueid.ts#L1

Is there any opportunity to make this Deno compatible?

**Comment by yordis** [comment]
keep

**Comment by yordis** [comment]
Security is the biggest reason I would love to use Deno over NodeJS. Deno has a secured sandbox that I can trust these types of tools without so much burden.

Over and over, NodeJS and NPM packages have proven that it is pretty easy to be vulnerable to malicious actors and that it is quite hard to trust the nightmare of `node_modules` dependencies.

Aside from that, not relying on NPM to be able to use some components is quite a fantastic experience since, in combination with the Deno secured sandbox, you can trust a bit more such imports.

---

I am more than happy to try to make this work with your support, but I am not sure what would be a proper direction here.

**Comment by mrgrain** [comment]
Should be supported by [Deno 2.0](https://docs.deno.com/runtime/reference/migration_guide/)
We are not going to offer any more support beyond this.
