### ISSUE TITLE
Async code in constructor

### ISSUE THREAD

**Issue by shishkin** [aws/constructs#888]
Hi! How can I execute async code in construct's constructor? Javascript/Typescript constructors disallow `await`. I would like to have an async build step before passing results onto sub-constructs.

**Comment by Chriscbr** [comment]
Unfortunately we do not generally support this kind of use case. Please see our guidance here: https://github.com/aws/aws-cdk/issues/8273#issuecomment-640537378

**Comment by shishkin** [comment]
Thanks for the pointer @Chriscbr, even though I totally disagree with that comment's reasoning as a few others did in that thread.

**Comment by mrgrain** [comment]
Irrespectively of opinions, this is not possible with JavaScript. You are looking for a functional version of `Constructs` and that is not a direction this library wants to go.
