### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by moltar** [aws/constructs#970]
Could you please include release notes with each release, even if these are just generated from PR titles? This would help to evaluate upgrades. Thanks.

**Comment by akash1810** [comment]
It looks like new releases are made when `devDependencies` are (automatically) upgraded. For example, see the [change set between v10.0.112 and v10.0.113](https://github.com/aws/constructs/compare/v10.0.112...v10.0.113).

AFAIK it's not necessary to publish a new version upon changes to `devDependencies`.

It's also undesirable from the POV of consuming repositories as it creates a lot of noise in the form of Dependabot PRs in those repositories.

**Comment by moltar** [comment]
Agree with @akash1810, but it's probably a separate issue from this one.

**Comment by mrgrain** [comment]
We do, unless it's chores and because we used to publish daily dependency upgrades (which are chores) they were missing release notes. We are not doing this anymore though. Closing.
